require("config.lazy")
require("config.keymaps")
require("config.colors")
require("config.config")


require("plugins.neotree")
require("plugins.treesiter")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.commit")
require("plugins.auto-save")
