require("config.lazy")
require("config.keymaps")
require("config.colors")
require("config.config")


require("plugins.neotree")
require("plugins.treesiter")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.commit")
require("plugins.auto-save")
--require("plugins.neotest")
require("plugins.neodev")
--require("plugins.nvim-dap-python")
require('plugins.catppuccin')
require('plugins.treesitter-refactor')
