require("config.lazy")
require("config.keymaps")
require("config.colors")
require("config.config")


require("plugins.telescope")
require("plugins.neotree")
require("plugins.treesiter")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.bufferline")
require("plugins.lualine")
--require("plugins.neotest")
--require("plugins.neodev")
--require("plugins.nvim-dap-python")
require("plugins.catppuccin")
require("plugins.mason")
require("plugins.null-ls")
